- .vscode/settings.json
- about.css
- about.html
- index.html
Added Success story Section.
Improved UI and Re-designed About Us page.
solved issue #10
> Added Success Story Section and Improved UI of About Page

- styles.css
I have made the suggested changes in the navbar.
> Navbar fixed

- Privacy policy.html
- TREMS AND SERVICE.CSS
- Trems and service.html
- privacy policy.css
Screenshot of the change
- Added animations headers
- change the color of headers 
- Added animations and color in main section
- Added responsiveness 
This is the solution of the issue #14
> Improved terms and privacy page design

- contributors/contributor.css
- contributors/contributor.html
- contributors/contributor.js
- index.html
> contributors page added in navbar

- index.html
- styles.css
**Description:**
This pull request introduces a fully functional **Scroll-to-Top Button** to enhance the user experience of the project. The feature is designed to make navigation more convenient, particularly for pages with extensive content. Below are the detailed aspects of this implementation:
- The button is circular in shape with a modern, minimalist design.
- Utilizes the Font Awesome `fa-arrow-up` icon to provide a clear visual indicator of its purpose.
- The button is positioned at the bottom-right corner of the screen for easy accessibility without interfering with the main content.
---
- The button remains hidden by default and appears only when the user scrolls down 20px from the top of the page.
- This ensures the button is non-intrusive and visible only when needed.
---
- …
> updating the scroll button to the homepage

- catalog2.css
- catalog2.html
Hey @vishantrathi  here are the changes i committed in catalog2 with video:
Flip Animation for Images:
Added a rotateY(180deg) flip effect on product images when hovered to reveal additional details.
Added Description, Price, and Product Name:
Integrated product details (name, description, price) into the flipped back of the card.
Fixed Alignment of Page:
Adjusted the layout for better alignment of product cards and other elements across the page.
Enhanced Responsiveness:
Improved media queries to make the layout responsive and adjust the number of product columns based on screen size.
UI/UX Improvements:
Enhanced hover effects, spacing, and alignment to improve user interaction and the overall appearance of the site.
https://github.com/user-attachments/assets/fa6d02fe-334c-4c75-9d20-b8f97 …
> changes how product appeared in catalog2

- Privacy policy.html
- Trems and service.html
- about.html
- contact.html
- contributors/contributor.html
- demand.html
- index.html
- navbar.css
- styles.css
This pr fixes issue #55 
The issue highlighted that the navbar's styling is inconsistent across different pages, with some pages like Contact Us, Privacy Policy, and Terms and Services lacking a navbar altogether. Additionally, the Log In and Sign Up buttons are not positioned intuitively, and the Contributors page could benefit from a different color scheme for the navbar.
To resolve this, I did the following:
- implemented a consistent navbar across all pages
- repositioned the Log In and Sign Up buttons to the left for better usability
- created a separate CSS file for the navbar
- adjusted the Contributors page navbar with an inverted color scheme
- I also removed the inconsistent navbars from pages like Demand and About Us
We can see that all pages have the same navbar, with the …
> Implemented consistent navbar and improved design, with improvements to contributors page as well

- signup.html
- signup.js
https://github.com/user-attachments/assets/bc52eda5-6de7-4977-8686-74ed7138069e
After this change, the application will check the user's password and confirm password before signup. The user will only be allowed to sign up if both passwords match.
> Password and Confirm password check

- .vscode/settings.json
- contact.css
- contact.html
solved #73 
https://github.com/user-attachments/assets/ebcb0094-9000-475b-8b51-f01dd838985c
> Added tooltips in the contact form

- contributors/contributor.css
- contributors/contributor.html
solved #76 
https://github.com/user-attachments/assets/1ef730e1-0141-4d05-bbd2-010d79885d97
> solved contributors page issue

- signup.html
Feature added and working properly, this solves issue #78
> Added show/hide options for password in signup.html

- Privacy policy.html
- TREMS AND SERVICE.CSS
- Trems and service.html
- about.css
- about.html
- contact.css
- contact.html
- demand.css
- demand.html
- index.html
- privacy policy.css
- styles.css
The issue encountered was the lack of consistency in the footer design and layout across various pages of the website. To address this, I ensured the footer remained uniform on all pages by standardizing its structure, design elements, and content.
I also enhanced the website's usability by making the email ID interactable. This involved converting the email address into a clickable mailto: link, enabling users to open their default email client and compose an email directly by clicking on the email address. 
https://github.com/user-attachments/assets/296ab8ce-856d-4775-92b4-a2b9da213f51
https://github.com/user-attachments/assets/630fdca5-14e2-4653-9d42-2ec389cac43d
Resolves: #63
> Inconsistent Footer across all pages

- about.html
- index.html
Scroll button also work properly now please check
Before-
After-
> I make some major changes on the Footer of the website. I hope you like this one.

- Privacy policy.html
- about.html
- contact.html
- demand.html
- privacy policy.css
Please checck-
https://github.com/user-attachments/assets/f2fc7731-8b55-4950-8195-f038399997eb
> Update footer on all Page.

- Privacy policy.html
- privacy policy.css
Added privacy Policy Page and Enhance the styling of the PrivacyPolicy Page , @vishantrathi , Add SWOC Labels to this PR .
Screenrecording : 
Uploading Screen Recording 2025-01-18 165433.mp4…
> Fixed and Enhance Privacy Policy Page

- terms and service.css
- terms and service.html
fixes #88 
redesigned terms and service page
> redesigned terms and service page

- terms and service.css
- terms and service.html
Fixed Terms and Services page , which matches the theme of the Website , Add SWOC labels to this PR @vishantrathi 
Screenrecording : 
https://github.com/user-attachments/assets/8ff4a167-000e-4be1-bdfd-bfc4751612f2
> Fixed Terms and Services Page

- contributors/contributor.css
- contributors/contributor.html
Hey @vishantrathi  ,
Could you Please review and let me know if any further updates are needed and merge this PR under SWOC. 😊
Here are changes : 
Before : 
https://github.com/user-attachments/assets/d2f770f0-3fd6-4a48-b9f6-d34fb76baa76
After Changes : 
https://github.com/user-attachments/assets/b0a6cef1-4d0a-439c-83a0-d78079f27edc
> Enhance Contributors Page

- index.html
- index.js
- signup.css
- signup.html
- signup.js
- styles.css
I have updated Navbar section and added animation using gsap with the help of timeline and stagger.
I have Updated Home section. i have added animation in Home section.
I have change Login/Sign Up Page.
Full UI Video
https://github.com/user-attachments/assets/48fbcb3a-6cb4-4cc3-b3b8-8fbc1dca1f6a
Login Page
Check This @vishantrathi
> I have Changed UI

- contributors/contributor.css
- contributors/contributor.js
Hey @vishantrathi  ,
Could you Please review and merge this PR under SWOC. 😊
As I work more in this PR , Add Intermediate level to this PR , 
Generated Certificate for Contributors , Which matches the Theme of the Website . 
Screenrecording : 
https://github.com/user-attachments/assets/0db0d79e-a2af-4655-8956-dab1bc009379
> Generate Certificate for Contributors

- index.html
- workwithus.css
- workwithus.html
- workwithus.js
Hey @vishantrathi ,
Could you Please review and merge this PR under SWOC. 😊
Screenrecording : 
https://github.com/user-attachments/assets/1b9cb6c7-ced0-485e-afe0-a2c657e757cf
> Added Work with Us Page

- Privacy policy.html
- about.html
- contact.html
- contributors/contributor.html
- demand.html
- index.html
- workwithus.html
#121 
@vishantrathi 
- I have added the payment options in the footers of the required files.
1. about.html
2. contact.html
3. demand.html
4. index.html
5. workingwithus.html
6. privacypolicy.html
7. contributores.html
footer results after adding payments options
-I hope there will be no conflicts.Inform me if any changes are required, and kindly add the necessary labels for my issue.
Thank you
> Adding payment options in footer #121

- catalog.html
- styles.css
The navbar was not consistent in the shopping page with some sections missing such as contributors page. Besides that some links were not working and the buttons were provided at the right hand corner unlike the other pages.
BEFORE
about us page
vs
shopping page
AFTER
> Shop navbar fixed
